import { isBeta } from './beta'
/* Novidades da plataforma: aparecem para quem usa assim que abre o sistema depois de uma
   atualização. Cada uma pode ter um "me mostra" que leva até a tela e destaca onde tocar.
   A mais nova fica em cima. Ao lançar algo novo, é só acrescentar aqui. */

export type NewsKind = 'novo' | 'melhoria' | 'correcao'
export interface NewsStep {
  text: string
  page?: string // tela para abrir (ex.: 'orcamentos')
  id?: string // parte da tela (ex.: 'novo' em orcamentos/novo)
  target?: string // o que destacar na tela (seletor)
  configTab?: string // abre esta aba das configurações
}
export interface News {
  id: string
  date: string // AAAA-MM-DD
  kind: NewsKind
  title: string
  text: string
  steps?: NewsStep[]
  feature?: import('./plans').Feature // só aparece para quem tem esta função no plano
  beta?: boolean // ainda em teste: só a dona (e a prévia) veem; quem assina vê quando sair o "beta"
}

export const NEWS_KIND: Record<NewsKind, { label: string; color: string }> = {
  novo: { label: 'novo', color: '#8f6d64' },
  melhoria: { label: 'melhoria', color: '#566779' },
  correcao: { label: 'correção', color: '#9aa3ab' },
}

export const NEWS: News[] = [
  {
    id: '2026-10-04-planos-claros',
    date: '2026-10-04',
    kind: 'melhoria',
    title: 'planos mais claros e contrato explicado',
    text: 'Os planos ficaram mais enxutos e alinhados, com a comparação completa logo abaixo. Em contratos, ficou claro como usar o texto do seu contrato: as cláusulas entram no modelo do planê, e para a sua identidade use o papel timbrado ou o PDF pronto.',
  },
  {
    id: '2026-10-04-pagar-indicar',
    date: '2026-10-04',
    kind: 'novo',
    title: 'pagar na hora e indicar amigos',
    text: 'Ao assinar, o Pix aparece com QR Code e código “copia e cola” já com o valor do plano, e o link do cartão quando houver. “Indique e ganhe” ganhou página própria no menu, com o seu link e mensagens prontas. Os dados de exemplo agora preenchem todas as telas, e as barras de rolagem ficaram discretas.',
    steps: [{ text: 'Seu link de indicação fica aqui.', page: 'indique' }],
  },
  {
    id: '2026-10-04-instagram-manual',
    date: '2026-10-04',
    kind: 'melhoria',
    title: 'instagram mais completo e manual mais simples',
    text: 'No instagram, o botão “montar texto” escreve cada postagem (gancho, slides, legenda e chamada) com os seus dados, sem custo, e a estratégia ganhou um montador de bio com contagem de caracteres. O manual agora tem busca no topo e passos mais curtos, com os detalhes guardados em “mais detalhes”.',
    steps: [{ text: 'Experimente a busca do manual.', page: 'manual' }],
  },
  {
    id: '2026-10-04-app-pdf',
    date: '2026-10-04',
    kind: 'correcao',
    title: 'PDF no app do celular',
    text: 'Com o planê instalado na tela inicial, os PDFs e arquivos agora são salvos ou compartilhados direto do app, sem precisar abrir o site. O menu lateral ganhou um fundo levemente destacado.',
  },
  {
    id: '2026-10-04-indique',
    date: '2026-10-04',
    kind: 'novo',
    title: 'indique e ganhe',
    text: 'Em “minha assinatura” você tem um link só seu. Quem se cadastrar por ele ganha 20% de desconto no primeiro mês, e você ganha 1 mês grátis quando a pessoa assinar. Dá para mandar direto no WhatsApp e acompanhar quem já veio.',
    steps: [{ text: 'Seu link fica em minha assinatura.', page: 'assinatura' }],
  },
  {
    id: '2026-10-04-contrato-folha',
    date: '2026-10-04',
    kind: 'novo',
    title: 'contrato na sua folha e modelos iguais em tudo',
    text: 'No contrato, escolha o desenho da folha: o modelo do planê, o seu papel timbrado (anexe a imagem ou o PDF da sua folha e o texto entra por cima, preenchido sozinho) ou um PDF pronto, que o cliente assina exatamente como é. Os 4 modelos (coluna, faixa, planilha e editorial) agora valem em todos os documentos, inclusive os de obra. E no plano sem PDF, o recibo também sai em texto pronto para copiar.',
    steps: [{ text: 'Abra um contrato e veja “desenho da folha”.', page: 'contratos' }],
  },
  {
    id: '2026-10-04-ajustes',
    date: '2026-10-04',
    kind: 'melhoria',
    title: 'mais fácil no dia a dia',
    text: 'Orçamento sem PDF ganhou o botão “copiar orçamento”, completo e organizado para WhatsApp ou e-mail. Rascunhos e enviados também arrastam no quadro de demandas. Os documentos de obra têm 4 layouts bem diferentes (tabela, índice, painel de referências e ficha técnica). Foto “encaixada inteira” preenche o espaço sem faixas brancas. E ao fechar algo sem salvar, o planê pergunta antes.',
    steps: [{ text: 'Para pôr o planê na tela do celular: menu → app no celular.', page: 'inicio' }],
  },
  {
    id: '2026-10-03-documentos-de-obra',
    date: '2026-10-03',
    kind: 'novo',
    title: 'documentos de obra',
    text: 'Memorial descritivo, lista de compras, custos de obra, diário de obra, relatório de visita com checklist, ata de reunião e ordem de serviço. Cada item tem valor, quantidade, descrição, link e foto; escolha entre 4 layouts (tabela, lista, cartões ou fichas), baixe o PDF com a sua marca e mostre no painel do cliente.',
    steps: [
      { text: 'Em documentos → de obra, ou dentro da demanda, na aba obra.', page: 'documentos' },
    ],
  },
  {
    id: '2026-10-03-menu-e-modelos',
    date: '2026-10-03',
    kind: 'melhoria',
    title: 'menu do seu jeito e documentos como modelos',
    text: 'O menu se ajusta a como você trabalha: quem só presta serviço para escritórios não vê o que é de cliente final. Em “organizar menu”, toque no olho para esconder ou mostrar cada tela. Em documentos, cada peça agora é o seu modelo: escolha entre os modelos prontos, cores, fontes e fotos e salve como padrão. Para um cliente, use “usar para um cliente”.',
    steps: [
      { text: 'Organizar menu fica no fim do menu lateral.', page: 'inicio' },
      { text: 'Seus modelos em documentos.', page: 'documentos' },
    ],
  },
  {
    id: '2026-10-03-agenda-quadro-capa',
    date: '2026-10-03',
    kind: 'melhoria',
    title: 'agenda mais completa, cartões que arrastam e capa ajustável',
    text: 'Na agenda, cada compromisso agora tem horário de término, local e cliente, e o tipo "pessoal" fica separado do trabalho. As demandas aparecem com o número do orçamento, sem confundir nomes iguais. No quadro de demandas, arraste os cartões entre as colunas, também no celular (segure um instante e arraste). E a foto de capa do painel do cliente dá para enquadrar e aproximar.',
    steps: [
      { text: 'Novo compromisso na agenda.', page: 'agenda' },
      { text: 'Arraste um cartão no quadro de demandas.', page: 'projetos' },
      { text: 'Capa em painel do cliente → aparência e topo.', page: 'paineis' },
    ],
  },
  {
    id: '2026-10-03-briefing-fotos',
    date: '2026-10-03',
    kind: 'melhoria',
    title: 'briefing: fotos à vontade, com legenda e explicação',
    text: 'Nas perguntas com foto, coloque quantas opções quiser: a grade se arruma sozinha, sempre equilibrada. Cada foto tem legenda e uma explicação curta embaixo. E as cores e paletas prontas agora dão para ajustar no tom que você quiser, ou trocar por uma foto sua.',
    steps: [{ text: 'Abra um modelo em briefings e escolha "com foto" numa pergunta de opções.', page: 'briefings' }],
  },
  {
    id: '2026-10-03-seguranca-e-pix',
    date: '2026-10-03',
    kind: 'novo',
    title: 'histórico de versões e chave Pix com tipo',
    text: 'O planê agora guarda sozinho como a sua conta estava, várias vezes por semana e sempre que muita coisa some de uma vez. Apagou algo sem querer? Em configurações → dados, volte para uma versão anterior. E a chave Pix ganhou o tipo (celular, CPF, CNPJ, e-mail ou aleatória), com a pontuação certinha.',
    steps: [
      { text: 'Histórico de versões em configurações → dados.', page: 'config', configTab: 'dados' },
      { text: 'Chave Pix no seu perfil.', page: 'perfil' },
    ],
  },
  {
    id: '2026-10-03-plane',
    date: '2026-10-03',
    kind: 'novo',
    title: 'agora somos planê',
    text: 'A plataforma ganhou nome definitivo: planê. Tudo continua igual por dentro, com os seus dados e configurações. Contato: equipe.plane@gmail.com · Instagram @sou.plane · useplane.com.br.',
  },
  {
    id: '2026-10-03-leitura-pdf',
    date: '2026-10-03',
    kind: 'correcao',
    title: 'PDF anexado lido do jeito certo',
    text: 'Contratos, manuais e briefings em PDF (inclusive os feitos no Canva) entram sem números repetidos ou grudados, com as colunas separadas e os títulos no lugar. No briefing, as bolinhas e quadradinhos viram opções de marcar e cada foto vai para a opção dela.',
  },
  {
    id: '2026-10-01-aparencia-todos',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'aparência do sistema liberada em todos os planos',
    text: 'Paletas, cores, fontes e tema do sistema agora podem ser escolhidos em qualquer plano. Levar o logo, as cores e as fontes para os PDFs e documentos continua no plano Completo.',
    steps: [{ text: 'Em configurações → aparência.', page: 'config', configTab: 'aparencia' }],
  },
  {
    id: '2026-10-01-comprovante-assinante',
    date: '2026-10-01',
    kind: 'novo',
    title: 'comprovante do assinante',
    text: 'No painel da plataforma, cada assinante tem o “comprovante do assinante”: um PDF com cadastro, aceite dos termos, pedido, pagamentos, acessos, uso da conta e conversas, para anexar numa contestação de pagamento.',
    beta: true,
  },
  {
    id: '2026-10-01-docs-painel',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'documentos novos já vão para o painel do cliente',
    text: 'Documento ou contrato novo de um cliente que tem painel já aparece no painel dele; se não quiser mostrar, é só desmarcar em “o que o cliente vê”. Na aba documentos, proposta, recibo e contrato ganharam a miniatura com o seu modelo.',
  },
  {
    id: '2026-10-01-contrato-anexado-e-layouts',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'contrato anexado no modelo do sistema e layout por documento',
    text: 'Ao anexar o seu contrato (Word ou PDF), o texto entra no modelo de contrato com a sua marca: cláusulas viram títulos, o cabeçalho do papel timbrado sai e tudo fica editável, com “ver como fica”. Se quiser, dá para tentar o desenho do arquivo. E cada documento (guia de medição, placa, briefing, apresentação e recibo) agora pode ter o próprio modelo de layout, escolhido no próprio documento. O menu também ficou na ordem mais usada.',
  },
  {
    id: '2026-10-01-fechamento-e-contrato-pdf',
    date: '2026-10-01',
    kind: 'novo',
    title: 'mensagem de fechamento e contrato em PDF com o seu desenho',
    text: 'No orçamento, “mensagem de fechamento” monta o texto para o WhatsApp com o valor negociado, a entrada e como fica o restante, e o Pix sai separado para copiar. E o contrato anexado em PDF agora mantém o desenho (títulos, negrito, centralizado, listas) e continua editável, como já acontecia com o Word.',
  },
  {
    id: '2026-10-01-servicos-organizados',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'sua tabela de serviços organizada',
    text: 'Os serviços que estavam em “outros” foram para as áreas certas (3D, desenho técnico, apresentação…), e repetidos que não estavam em nenhum orçamento viraram um só. Valores e orçamentos já feitos continuam exatamente iguais.',
    steps: [{ text: 'Veja em configurações → preços.', page: 'config', configTab: 'precos' }],
  },
  {
    id: '2026-10-01-painel-personalizado',
    date: '2026-10-01',
    kind: 'novo',
    title: 'painel do cliente com a sua cara',
    text: 'O painel agora usa as cores da sua identidade em três estilos (suave, marcante e claro). Dá para colocar foto de capa, um texto de boas-vindas seu, o próximo encontro com o cliente e escolher quais seções aparecem. A página dos painéis ganhou um resumo no topo e os valores pagos somam todos os projetos, igual ao que o cliente vê.',
    steps: [{ text: 'Em painel do cliente, toque em “editar ao vivo” e veja “aparência e topo do painel”.', page: 'paineis' }],
  },
  {
    id: '2026-10-01-fonte-propria-texto',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'sua fonte também nos textos',
    text: 'Em configurações → aparência, além da fonte dos títulos, agora dá para enviar um arquivo de fonte seu para os textos. Vale para o sistema e para os documentos.',
    steps: [{ text: 'Em aparência, desça até “fonte do texto” e toque em “usar uma fonte minha”.', page: 'config', configTab: 'aparencia' }],
  },
  {
    id: '2026-10-01-urgencia-opcional',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'taxa de urgência sem aparecer no PDF',
    text: 'No orçamento com urgência, escolha se o valor da taxa aparece no PDF. Desmarcando, ela fica embutida no valor de cada serviço e o total continua o mesmo.',
  },
  {
    id: '2026-10-01-catalogo-servicos',
    date: '2026-10-01',
    kind: 'novo',
    title: 'lista de serviços bem mais completa',
    text: 'Ao adicionar serviços, agora tem dezenas de opções organizadas por área: arquitetura, interiores, projetos técnicos, obra, 3D, consultoria e, para quem atende escritórios, desenho técnico, detalhamento, apresentação e planejamento. Cada um já vem com a forma de cobrar e um valor de partida, e tem busca para achar rápido.',
    steps: [{ text: 'Em configurações → preços, toque em “adicionar serviço”.', page: 'config', configTab: 'precos' }],
  },
  {
    id: '2026-10-01-ia-valor-tabela',
    date: '2026-10-01',
    kind: 'correcao',
    title: 'valor da IA acompanha a tabela',
    text: 'No orçamento preenchido pela IA, ao mudar m², quantidade, complexidade ou pavimentos, o valor passa a seguir a sua tabela de preços. O botão “usar tabela” mostra o valor da tabela antes de trocar.',
    beta: true,
  },
  {
    id: '2026-10-01-celular-alinhado',
    date: '2026-10-01',
    kind: 'correcao',
    title: 'botões alinhados no celular',
    text: 'Os ícones do topo ficaram do mesmo tamanho e alinhados, e os botões de orçamentos, contratos, demandas e clientes se organizam sem sobrar um sozinho embaixo. Ações menos usadas ficam em “mais”. Na sugestão de orçamento da IA, nomes longos e botões cabem certinho.',
  },
  {
    id: '2026-10-01-rolagem-celular',
    date: '2026-10-01',
    kind: 'correcao',
    title: 'rolagem mais leve no celular',
    text: 'A tela rola fluida no celular, sem trancos. No orçamento, a proposta cabe inteira na tela e o topo rola junto com a página.',
  },
  {
    id: '2026-10-01-ia-para-orcamento',
    date: '2026-10-01',
    kind: 'novo',
    title: 'da IA direto para o orçamento',
    text: 'Quando o assistente sugerir valor e escopo, aparece o orçamento sugerido, com cada serviço separado, e o botão "criar orçamento com isso": ele pergunta se é para cliente final ou terceirização e abre o orçamento já preenchido, para você editar tudo.',
    feature: 'assistenteIA',
  },
  {
    id: '2026-10-01-painel-cliente-novo',
    date: '2026-10-01',
    kind: 'novo',
    title: 'painel do cliente de cara nova',
    text: 'O painel que o cliente abre pelo link agora usa as cores da sua marca, mostra o quanto do projeto já está pronto, a linha das etapas com símbolos, quando fica pronto, pagamentos e documentos, e um "para você fazer" com botões (assinar, responder, copiar o Pix).',
    feature: 'portal',
    steps: [{ page: 'paineis', text: 'Em "painel do cliente", toque em "ver como o cliente vê".' }],
  },
  {
    id: '2026-10-01-briefing-fotos',
    date: '2026-10-01',
    kind: 'novo',
    title: 'briefing com as suas fotos',
    text: 'Nas perguntas de escolha, coloque 2, 3, 4 ou 6 fotos suas como opções; os espaços vazios mostram "adicione sua referência". O briefing anexado do Word já traz as fotos de cada opção, e a prévia mostra como fica no computador e no celular.',
    feature: 'briefing',
    steps: [{ page: 'briefings', text: 'Abra um modelo e escolha "fotos nas opções" numa pergunta de escolha.' }],
  },
  {
    id: '2026-10-01-documentos-todos',
    date: '2026-10-01',
    kind: 'novo',
    title: 'todos os PDFs em documentos',
    text: 'Proposta, recibo, contrato e os documentos do estúdio agora ficam juntos em "documentos", com a aba "modelo e padrões". Cada PDF tem a aparência ali mesmo: modelo, cores da marca, fontes e logotipo.',
    steps: [{ page: 'documentos', text: 'No menu, "documentos" reúne tudo.' }],
  },
  {
    id: '2026-10-01-contrato-modelo-word',
    date: '2026-10-01',
    kind: 'novo',
    title: 'seu contrato com o seu desenho',
    text: 'Anexando o contrato do Word, ele fica igual ao seu arquivo (negrito, cores, tabelas, listas e imagens), editável direto na folha e com prévia.',
    feature: 'contratos',
    steps: [{ page: 'contratos', text: 'Toque em "anexar meu contrato".' }],
  },
  {
    id: '2026-10-01-metas-perfil',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'metas e para quem você trabalha',
    text: 'Meta do ano para qualquer formato (não só MEI) e, em configurações, a escolha de trabalhar para freelancer, cliente final ou os dois. A lista de demandas também ficou mais organizada.',
  },
  {
    id: '2026-10-01-documentos-aparencia',
    date: '2026-10-01',
    kind: 'melhoria',
    title: 'aparência dentro de cada documento',
    text: 'Guia de medição, placa de obra, briefing em PDF e apresentação agora têm, ali mesmo, a escolha do modelo, as cores do seu site e o logotipo. A placa também mostra o seu logo.',
    feature: 'documentos',
    steps: [{ page: 'documentos', text: 'Abra um documento: a parte "aparência" fica no topo.' }],
  },
  {
    id: '2026-10-01-datas-antigos',
    date: '2026-10-01',
    kind: 'correcao',
    title: 'datas certas para orçamentos antigos',
    text: 'Orçamentos antigos sem número entram no financeiro na data do orçamento, não no dia em que foram lançados. Se algum entrou no mês errado, o financeiro mostra um aviso para corrigir. A data de entrega também dá para mudar direto no painel do cliente.',
    steps: [{ page: 'financeiro', text: 'Se aparecer o aviso no topo, toque em "ver e corrigir".' }],
  },
  {
    id: '2026-09-30-painel-cliente-completo-resumo',
    date: '2026-09-30',
    kind: 'novo',
    title: 'painel do cliente e propostas',
    text: 'O painel do cliente ficou mais completo e agora você edita vendo ao vivo o que ele vê. A proposta de cliente final também pode sair em folha única.',
    steps: [{ page: 'paineis', text: 'No menu, "painel do cliente" mostra todos os seus clientes.' }],
  },
  {
    id: '2026-09-30-termometro-uso-resumo',
    date: '2026-09-30',
    kind: 'novo',
    title: 'termômetro de uso',
    text: 'No painel, veja quem está usando de verdade: só números, sem abrir o conteúdo das contas.',
    feature: 'painelDona',
  },
  {
    id: '2026-09-30-tabela-precos-simples-resumo',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'tudo mais simples e do seu jeito',
    text: 'Tabela de preços mais fácil, modelos com as suas cores e logotipo, fotos que você recorta ou encaixa e rascunho guardado se fechar algo sem querer.',
    steps: [{ page: 'config', configTab: 'precos', text: 'Em configurações → preços, toque num serviço para mudar.' }],
  },
  {
    id: '2026-09-30-regularizacao-resumo',
    date: '2026-09-30',
    kind: 'novo',
    title: 'regularização de imóvel',
    text: 'Etapas e briefing prontos para regularização. E as funções de outros planos agora aparecem para você conhecer.',
  },
  {
    id: '2026-09-30-briefing-proprio',
    date: '2026-09-30',
    kind: 'novo',
    title: 'use o seu próprio briefing',
    feature: 'briefing',
    text: 'Já tem um briefing seu?',
    steps: [{ page: 'briefings', text: 'Em briefings, toque em “anexar meu briefing”.' }],
  },
  {
    id: '2026-09-30-anual-contrato-proprio',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'anual com 2 meses grátis e contrato próprio',
    text: 'No plano anual você ganha 2 meses grátis: à vista no Pix ou em 12x sem juros no cartão.',
    steps: [{ page: 'contratos', text: 'Em contratos, toque em “anexar meu contrato”.' }],
  },
  {
    id: '2026-09-30-painel-cliente',
    date: '2026-09-30',
    kind: 'novo',
    title: 'painel do cliente',
    feature: 'portal',
    text: 'Cada cliente pode ter um painel só dele, aberto pelo link que você manda: etapas, pagamentos, contratos para assinar, briefings, documentos e arquivos que você escolher.',
    steps: [{ page: 'clientes', text: 'Abra um cliente e toque em “criar o painel”.' }],
  },
  {
    id: '2026-09-30-central-avisos',
    date: '2026-09-30',
    kind: 'novo',
    title: 'avisos quando o cliente preenche algo',
    text: 'Briefing respondido, contrato assinado ou recado pelo painel: chega aviso no topo do sistema (ícone da caixa) e no seu e-mail.',
  },
  {
    id: '2026-09-30-tela-inicio',
    date: '2026-09-30',
    kind: 'novo',
    title: 'planê na tela de início do celular',
    text: 'Dá para adicionar o planê como um ícone no celular, que abre em tela cheia como um aplicativo.',
    steps: [{ page: 'perfil', text: 'No perfil, veja “no celular”.' }],
  },
  {
    id: '2026-09-30-briefing-contrato-mais',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'briefing, assinatura e documentos mais completos',
    text: 'Briefing respondido pode ser baixado em PDF e você recebe um aviso no aparelho quando o cliente termina; o cliente pode guardar uma cópia das respostas.',
    steps: [{ page: 'briefings', text: 'Abra um briefing respondido para baixar o PDF.' }],
  },
  {
    id: '2026-09-30-assinatura',
    date: '2026-09-30',
    kind: 'novo',
    title: 'contrato assinado pelo celular',
    text: 'No contrato, a nova seção "assinatura": mande um link e o cliente lê e assina desenhando com o dedo (ou com o nome digitado).',
    steps: [{ page: 'contratos', text: 'Abra um contrato e veja a seção assinatura.' }],
  },
  {
    id: '2026-09-30-funil-etapas',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'funil do mês e aviso de parcela por etapa',
    text: 'Em orçamentos, o funil mostra quantos briefings viraram proposta e quantas fecharam.',
    steps: [{ page: 'orcamentos', text: 'Veja o funil do mês.' }],
  },
  {
    id: '2026-09-30-demandas-contratos',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'demandas, contratos e manual mais claros',
    text: 'No quadro de demandas, rascunhos e enviados aparecem como orçamentos ainda não fechados, com um resumo do que está em negociação e do que fechou no mês.',
    steps: [{ page: 'projetos', text: 'Veja o resumo no topo das demandas.' }, { page: 'manual', text: 'Abra o manual e escolha o seu plano.' }],
  },
  {
    id: '2026-09-30-celular',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'mais confortável no celular',
    text: 'A busca abre por cima da barra ao tocar, os botões ficam organizados em grade e, onde uma opção avançada fica só no computador, aparece um aviso curto dizendo isso.',
  },
  {
    id: '2026-09-30-estudio-para-todos',
    date: '2026-09-30',
    kind: 'novo',
    title: 'agora também para quem atende cliente final',
    text: 'O planê nasceu para freelancers e, a pedido de várias arquitetas, agora também é para quem projeta direto para o cliente final: briefing online com imagens, cronograma das etapas, obra, página do projeto para o cliente, proposta em slides e documentos com a sua marca.',
    steps: [{ page: 'briefings', text: 'Comece mandando um briefing para um cliente.' }, { page: 'documentos', text: 'Veja os documentos: guia de medição, placa de obra e apresentação.' }],
  },
  {
    id: '2026-09-30-documentos-v2',
    date: '2026-09-30',
    kind: 'novo',
    title: 'documentos do estúdio',
    text: 'Guia de medição com desenhos explicando cada medida, placa de obra com QR code (4 layouts), briefing em PDF para imprimir e apresentação de projeto em slides.',
    steps: [{ page: 'documentos', text: 'Abra “documentos” no menu e escolha um.' }],
  },
  {
    id: '2026-09-30-briefing-imagens-v2',
    date: '2026-09-30',
    kind: 'novo',
    title: 'briefing com imagens e sub-perguntas',
    text: '21 modelos prontos (studio, dormitório infantil, arquitetônico, clínica, área gourmet, closet, salão, restaurante, loja, igreja…).',
    steps: [{ page: 'briefings', text: 'Em “briefings”, toque em “editar” num modelo ou em “mandar”.' }],
  },
  {
    id: '2026-09-30-orcamento-para-quem',
    date: '2026-09-30',
    kind: 'melhoria',
    title: 'orçamento: para quem é, explicado',
    text: 'Ao criar um orçamento você escolhe cliente final (proposta em slides, com o tipo de projeto e as etapas) ou freelancer / escritório parceiro.',
    steps: [{ page: 'orcamentos', id: 'novo', text: 'Toque em “novo orçamento”.' }, { page: 'processos', text: 'Suas etapas de trabalho (cliente final, freelancer e estudante) ficam em “etapas de trabalho”.' }],
  },
  {
    id: '2026-09-30-correcoes',
    date: '2026-09-30',
    kind: 'correcao',
    title: 'correções',
    text: 'O link do briefing e a página do projeto para o cliente agora abrem sempre.',
  },
  {
    id: '2026-09-29-orcamento-cliente-final',
    date: '2026-09-29',
    kind: 'novo',
    title: 'orçamento para cliente final, em slides',
    text: 'Ao criar um orçamento, você escolhe para quem é: cliente final ou escritório parceiro.',
    steps: [
      { page: 'orcamentos', text: 'Clique em “novo” e escolha “cliente final”.' },
      { page: 'config', text: 'Em configurações → propostas, edite seus processos (interiores, arquitetônico, consultoria online) e coloque as fotos dos seus projetos.' },
    ],
  },
  {
    id: '2026-09-29-estudio-abas',
    date: '2026-09-29',
    kind: 'novo',
    title: 'demandas com abas',
    text: 'Cada demanda agora tem abas: visão geral, cronograma, obra, custos e lucro e página do cliente.',
    steps: [{ page: 'projetos', text: 'Abra uma demanda: as abas ficam logo abaixo dos cartões do topo.' }],
  },
  {
    id: '2026-09-29-tres-planos',
    date: '2026-09-29',
    kind: 'novo',
    title: 'agora são três planos',
    text: 'Além do Essencial e do Completo, chegou o Estúdio: tudo do Completo e os recursos para quem atende cliente final.',
    steps: [{ page: 'assinatura', text: 'Em minha assinatura, veja o que cada plano tem.' }],
  },
  {
    id: '2026-09-29-cliente-final',
    date: '2026-09-29',
    kind: 'novo',
    title: 'para quem atende cliente final',
    text: 'Agora o sistema se adapta a como você trabalha: freelancer, quem atende cliente final ou os dois.',
    steps: [
      { page: 'config', configTab: 'dados', target: '.wp-options', text: 'Em configurações → dados, escolha “como você trabalha”.' },
      { page: 'clientes', text: 'Ao cadastrar um cliente, escolha o tipo “cliente final”: aparecem os campos da família e do imóvel.' },
    ],
  },
  {
    id: '2026-09-29-briefing',
    date: '2026-09-29',
    kind: 'novo',
    title: 'briefing online completo',
    text: 'No plano Estúdio, o menu “briefings” tem modelos prontos (residencial, comercial, arquitetônico, cozinha, banheiro, quarto, sala, home office) que você edita como um formulário: perguntas de texto, de marcar, datas e fotos.',
    steps: [{ page: 'briefings', text: 'Em briefings, escolha um modelo e toque em “mandar”.' }],
  },
  {
    id: '2026-09-29-tabela-grupos',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'tabela de preços organizada em grupos',
    text: 'Os serviços podem ter grupo (ex.: projeto, projetos complementares, regularização, obra).',
    steps: [{ page: 'config', configTab: 'precos', text: 'Em configurações → preços, cada serviço tem o campo “grupo”.' }],
  },
  {
    id: '2026-09-29-instagram-formatos',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'instagram: escolha story, reels ou post',
    text: 'Ao tocar num dia do calendário, escolha o formato primeiro: story, reels ou post. Aí aparecem as ideias daquele formato.',
    steps: [{ page: 'instagram', text: 'Toque num dia do calendário e escolha um dos três cartões.' }],
  },
  {
    id: '2026-09-29-chat-formatacao',
    date: '2026-09-29',
    kind: 'novo',
    title: 'chat com negrito, itálico, sublinhado e emojis',
    text: 'Na conversa com o assistente online agora dá para destacar palavras e colocar emojis. Selecione o texto e toque em N, I ou S; o 😊 abre os emojis.',
    steps: [{ text: 'Toque no balão de conversa, no canto da tela: a barrinha de formatação fica em cima da caixa de escrever.' }],
  },
  {
    id: '2026-09-29-avisos-resposta',
    date: '2026-09-29',
    kind: 'novo',
    title: 'aviso quando respondemos você',
    text: 'Quando respondermos sua mensagem ou sua sugestão mudar de situação (em análise, planejada, feita…), você recebe um aviso na tela e por e-mail.',
    steps: [{ page: 'sugestoes', text: 'Em sugestões, as que tiveram resposta nova aparecem destacadas.' }],
  },
  {
    id: '2026-09-29-instagram-calendario',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'instagram: toque no dia para planejar',
    text: 'O calendário do instagram aparece sempre. Toque em qualquer dia para ver sugestões de postagem para ele e escolher uma, ou começar em branco.',
    steps: [{ page: 'instagram', target: '.ig-cell, .ig-mini-day', text: 'Toque em um dia do calendário: aparecem as sugestões para aquele dia.' }],
  },
  {
    id: '2026-09-29-instagram-sugestao',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'planejar o mês do instagram do seu jeito',
    text: 'O “planejar mês” agora mostra a sugestão antes: você escolhe quais postagens quer e ajusta dia, formato e tema de cada uma.',
    steps: [{ page: 'instagram', text: 'Toque em “planejar mês”, marque as postagens que quer, ajuste o que precisar e toque em “adicionar ao calendário”.' }],
  },
  {
    id: '2026-09-29-cantos',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'cantos arredondados do seu jeito',
    text: 'A régua de cantos arredondados agora vale para tudo, aos poucos: botões, etiquetas e campos acompanham, do reto ao bem redondo.',
    steps: [{ page: 'config', configTab: 'aparencia', text: 'Em aparência, arraste “cantos arredondados” e veja tudo mudando junto.' }],
  },
  {
    id: '2026-09-29-encerrar-conta',
    date: '2026-09-29',
    kind: 'novo',
    title: 'desativar ou apagar a conta',
    text: 'Em minha assinatura, agora dá para desativar a conta (tudo fica guardado) ou apagar de vez, com a opção de baixar uma cópia antes.',
  },
  {
    id: '2026-09-29-seletor-cores',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'escolher cores ficou mais fácil',
    text: 'Nas cores do seu estúdio e da proposta, agora abre um seletor próprio: arraste para achar o tom, digite o código (HEX ou RGB) e reaproveite as cores que você usou por último.',
    steps: [{ page: 'config', configTab: 'aparencia', target: '.clr-swatch-btn', text: 'Toque na cor para abrir o seletor. As últimas cores escolhidas ficam guardadas em “recentes”.' }],
  },
  {
    id: '2026-09-29-status-no-quadro',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'aprovado ou recusado direto nas demandas',
    text: 'Nos cartões de orçamento (rascunhos e enviados) do quadro de demandas, agora dá para mudar a situação ali mesmo: enviado, aprovado, não fechou…',
    steps: [{ page: 'projetos', target: '.kcard-status', text: 'Escolha a situação aqui. Se for “aprovado”, abre a janela para criar a demanda com o valor fechado.' }],
  },
  {
    id: '2026-09-29-agenda-tipos',
    date: '2026-09-29',
    kind: 'melhoria',
    title: 'tipos da agenda com os seus nomes',
    text: 'Os tipos de compromisso agora são seus: troque “Estudos / faculdade”, “Reunião” e os outros pelos nomes que fazem sentido na sua rotina.',
    steps: [{ page: 'agenda', text: 'Toque em “+ Compromisso” e, no campo Tipo, em “renomear os tipos”. O nome novo vale para a agenda toda.' }],
  },
  {
    id: '2026-09-29-contrato-assinatura',
    date: '2026-09-29',
    kind: 'correcao',
    title: 'contrato com espaço de assinatura em branco',
    text: 'O contrato sai sem assinatura pronta: as duas partes assinam depois, no papel ou numa plataforma de assinatura digital (como gov.br, Clicksign ou DocuSign).',
  },
  {
    id: '2026-09-29-pacote-mensal',
    date: '2026-09-29',
    kind: 'novo',
    title: 'pacote ou parceria mensal',
    text: 'Cliente quer fechar vários serviços e pagar mês a mês?',
    steps: [
      { page: 'orcamentos', id: 'novo', target: '.q-months', text: 'Em “informações da proposta”, escolha em quantos meses o cliente vai pagar. Aparece na hora quanto fica por mês.' },
      { text: 'Dica: pacote fechado costuma ter 5% a 10% de desconto (botões ao lado do total). Ao aprovar, a demanda já nasce com uma parcela por mês, cada uma com a sua data.' },
    ],
  },
  {
    id: '2026-09-28-pix-cartao',
    date: '2026-09-28',
    kind: 'novo',
    title: 'Pix ou cartão ao receber',
    text: 'Ao marcar um pagamento como recebido, o sistema pergunta se foi Pix ou cartão.',
    steps: [{ page: 'config', configTab: 'propostas', target: '.cfg-card-fee', text: 'Coloque aqui a taxa que a sua maquininha ou o Mercado Pago cobra no crédito. O financeiro usa ela para mostrar o seu lucro certinho.' }],
  },
  {
    id: '2026-09-28-orcamento-antigo',
    date: '2026-09-28',
    kind: 'novo',
    title: 'orçamento antigo, sem número',
    text: 'Tem clientes de antes do sistema? Lance como “orçamento antigo”: fica fora da numeração e o financeiro entra nas datas reais.',
    steps: [{ page: 'orcamentos', target: '#btn-orcamento-antigo', text: 'Toque aqui, preencha como um orçamento normal com a data real e depois marque como aprovado, escolhendo “tudo” em “o que já foi pago”.' }],
  },
  {
    id: '2026-09-29-excluir-topo',
    date: '2026-09-29',
    kind: 'correcao',
    title: 'excluir orçamento pelo topo',
    text: 'A lixeira agora fica também no alto do orçamento, e excluir funciona mesmo com alterações ainda não salvas.',
  },
]

/** Novidades que a pessoa ainda não viu. */
/** As novidades que esta pessoa pode ver (as em teste só aparecem para a dona e na prévia). */
export const visibleNews = () => NEWS.filter((n) => !n.beta || isBeta())
export const unseenNews = (seen?: string[], has: (f: import('./plans').Feature) => boolean = () => true) => (seen ? visibleNews().filter((n) => !seen.includes(n.id) && (!n.feature || has(n.feature))) : [])
